Done homework.
Jyugo009/BlackJack pull request #1
Opened 2023-11-20 07:22 UTC by Jyugo009

2023-11-20 15:05 UTC, Delvin09 requested changes
Следи за форматированием и стилем, это влияет на читаемость кода.

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Card.cs
> +        public string _value { get; set; }
Поля с маленькой и/или с подчеркивания. А у тебя свойства, они с большой.
Вместо строк, лучше использовать enum's, тогда не будет проблем с подсчетом очков. Ну и оптимальнее будет

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Deck.cs
> +            Card[] spadesCards = cards.Where(card => card._suit == SuitSymbols["Spades"]).ToArray();
Можно же перестановками в один проход без доп памяти.

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Deck.cs
> +            Array.Resize(ref cards, cards.Length - 1);
Можно и без Resize, просто запоминать текущий индекс, и смещать его при взятии карты.

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +        private List<Card> _playerCards;
Почему не создать класс Игрок, и туда не инкапсулировать его карты и пр.?

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +        private bool GameOver()
`IsGameOver`

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +                if (!_playerContinues && !_computerContinues)
это можно в начало тела цикла вынести

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +            _deck = new Deck();
очень похоже на то, что есть в методе Reset

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +        private bool GameOver()
он гдето используется?

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +            while (true)
`playerChoice != "Y" && playerChoice != "N"` тогда в теле цикла останется только последний else, а остальные условия вынеси за цикл.

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +                if (_computerPoints >= 21)
при учете условия выше, в этом нет смысла

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +            int playerAces = _playerCards.Count(card => card._value == "Ace");
вообще, 2 туза это при начальной раздаче. т.е. когда DealInitialCards сдает игроку или комп. 2 туза, то тот автоматом выигрывает.

2023-11-20 15:05 UTC, Delvin09 commented on BlackJack/Game.cs
> +                string playerChoice = Console.ReadLine().ToUpper();
я думаю этот код с рестартом, нужно вынести в метод меин или в StartGame, иначе тут рекурсия получается...

2023-11-20 20:38 UTC, Jyugo009 commented on BlackJack/Deck.cs
> +            Array.Resize(ref cards, cards.Length - 1);
Решил тут отказаться от массива, в пользу Листа, при переработке логики под enums. Как будто бы, Лист больше подходит, когда дело касается изменения размеров коллекции?

2023-11-20 20:41 UTC, Jyugo009 commented on BlackJack/Game.cs
> +        private bool GameOver()
О... Забыл снести, когда реализовал по другому.

2023-11-20 20:47 UTC, Jyugo009 commented on BlackJack/Game.cs
> +            int playerAces = _playerCards.Count(card => card._value == "Ace");
> вообще, 2 туза это при начальной раздаче. т.е. когда DealInitialCards сдает игроку или комп. 2 туза, то тот автоматом выигрывает.

Так, это ошибка? Я подумал, что оно все равно при раздаче двух тузов срабатывает на >21 и сразу идет в метод определения победителя и первое, с чем сталкивается оказывается проверкой на наличие двух тузов и что при этом не больше 2х карт?

2023-11-20 22:01 UTC, Jyugo009 commented on BlackJack/Deck.cs
> +            Card[] spadesCards = cards.Where(card => card._suit == SuitSymbols["Spades"]).ToArray();
+

2023-11-20 22:01 UTC, Jyugo009 commented on BlackJack/Game.cs
> +        private List<Card> _playerCards;
++

2023-11-20 22:02 UTC, Jyugo009 commented on BlackJack/Game.cs
> +            _deck = new Deck();
++

2023-11-20 22:04 UTC, Jyugo009 commented on BlackJack/Game.cs
> +                if (!_playerContinues && !_computerContinues)
++

2023-11-20 22:19 UTC, Jyugo009 commented on BlackJack/Game.cs
> +            while (true)
++

2023-11-20 23:03 UTC, Jyugo009 commented on BlackJack/Game.cs
> +                if (_computerPoints >= 21)
++

2023-11-20 23:04 UTC, Jyugo009 commented on BlackJack/Game.cs
> +                string playerChoice = Console.ReadLine().ToUpper();
++

2023-11-21 08:34 UTC, Jyugo009 commented on BlackJack/Game.cs
> +            int playerAces = _playerCards.Count(card => card._value == "Ace");
И все же исправил.

2023-11-21 11:25 UTC, Delvin09 approved these changes

2023-11-21 11:26 UTC, merged